// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/pengjun/ka/net/protobuf/KeepAccount.proto

package com.pengjun.ka.net.protobuf;

public final class KaProtocol {
  private KaProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    REGISTER(0, 1),
    LOGIN(1, 2),
    BACKUP(2, 3),
    RESTORE(3, 4),
    ;
    
    public static final int REGISTER_VALUE = 1;
    public static final int LOGIN_VALUE = 2;
    public static final int BACKUP_VALUE = 3;
    public static final int RESTORE_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static MsgType valueOf(int value) {
      switch (value) {
        case 1: return REGISTER;
        case 2: return LOGIN;
        case 3: return BACKUP;
        case 4: return RESTORE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MsgType[] VALUES = {
      REGISTER, LOGIN, BACKUP, RESTORE, 
    };
    
    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MsgType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.pengjun.ka.net.protobuf.MsgType)
  }
  
  public enum MsgRply
      implements com.google.protobuf.ProtocolMessageEnum {
    SUCCESS(0, 1),
    FAILED(1, 2),
    ;
    
    public static final int SUCCESS_VALUE = 1;
    public static final int FAILED_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static MsgRply valueOf(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAILED;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MsgRply>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MsgRply>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgRply>() {
            public MsgRply findValueByNumber(int number) {
              return MsgRply.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final MsgRply[] VALUES = {
      SUCCESS, FAILED, 
    };
    
    public static MsgRply valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MsgRply(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.pengjun.ka.net.protobuf.MsgRply)
  }
  
  public interface ArProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 id = 1;
    boolean hasId();
    int getId();
    
    // required float account = 2;
    boolean hasAccount();
    float getAccount();
    
    // required int32 typeId = 3;
    boolean hasTypeId();
    int getTypeId();
    
    // required string createDate = 4;
    boolean hasCreateDate();
    String getCreateDate();
    
    // optional string comment = 5;
    boolean hasComment();
    String getComment();
    
    // required string updateTime = 6;
    boolean hasUpdateTime();
    String getUpdateTime();
  }
  public static final class ArProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ArProtocolOrBuilder {
    // Use ArProtocol.newBuilder() to construct.
    private ArProtocol(Builder builder) {
      super(builder);
    }
    private ArProtocol(boolean noInit) {}
    
    private static final ArProtocol defaultInstance;
    public static ArProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required float account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private float account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getAccount() {
      return account_;
    }
    
    // required int32 typeId = 3;
    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getTypeId() {
      return typeId_;
    }
    
    // required string createDate = 4;
    public static final int CREATEDATE_FIELD_NUMBER = 4;
    private java.lang.Object createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCreateDate() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          createDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreateDateBytes() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string comment = 5;
    public static final int COMMENT_FIELD_NUMBER = 5;
    private java.lang.Object comment_;
    public boolean hasComment() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          comment_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string updateTime = 6;
    public static final int UPDATETIME_FIELD_NUMBER = 6;
    private java.lang.Object updateTime_;
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          updateTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      account_ = 0F;
      typeId_ = 0;
      createDate_ = "";
      comment_ = "";
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCommentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCommentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArProtocol_fieldAccessorTable;
      }
      
      // Construct using com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDescriptor();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol getDefaultInstanceForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol build() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol buildPartial() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = new com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.comment_ = comment_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol) {
          return mergeFrom((com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol other) {
        if (other == com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasComment()) {
          setComment(other.getComment());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasTypeId()) {
          
          return false;
        }
        if (!hasCreateDate()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              account_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              typeId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              createDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              comment_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required float account = 2;
      private float account_ ;
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getAccount() {
        return account_;
      }
      public Builder setAccount(float value) {
        bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = 0F;
        onChanged();
        return this;
      }
      
      // required int32 typeId = 3;
      private int typeId_ ;
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTypeId() {
        return typeId_;
      }
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000004;
        typeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        typeId_ = 0;
        onChanged();
        return this;
      }
      
      // required string createDate = 4;
      private java.lang.Object createDate_ = "";
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCreateDate() {
        java.lang.Object ref = createDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          createDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreateDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createDate_ = getDefaultInstance().getCreateDate();
        onChanged();
        return this;
      }
      void setCreateDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
      }
      
      // optional string comment = 5;
      private java.lang.Object comment_ = "";
      public boolean hasComment() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setComment(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        comment_ = value;
        onChanged();
        return this;
      }
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000010);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      void setComment(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        comment_ = value;
        onChanged();
      }
      
      // required string updateTime = 6;
      private java.lang.Object updateTime_ = "";
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUpdateTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        updateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      void setUpdateTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        updateTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.pengjun.ka.net.protobuf.ArProtocol)
    }
    
    static {
      defaultInstance = new ArProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pengjun.ka.net.protobuf.ArProtocol)
  }
  
  public interface ArTypeProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string typeName = 2;
    boolean hasTypeName();
    String getTypeName();
    
    // required string imgResName = 3;
    boolean hasImgResName();
    String getImgResName();
    
    // required string createDate = 4;
    boolean hasCreateDate();
    String getCreateDate();
    
    // required string updateTime = 5;
    boolean hasUpdateTime();
    String getUpdateTime();
  }
  public static final class ArTypeProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ArTypeProtocolOrBuilder {
    // Use ArTypeProtocol.newBuilder() to construct.
    private ArTypeProtocol(Builder builder) {
      super(builder);
    }
    private ArTypeProtocol(boolean noInit) {}
    
    private static final ArTypeProtocol defaultInstance;
    public static ArTypeProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArTypeProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string typeName = 2;
    public static final int TYPENAME_FIELD_NUMBER = 2;
    private java.lang.Object typeName_;
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          typeName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string imgResName = 3;
    public static final int IMGRESNAME_FIELD_NUMBER = 3;
    private java.lang.Object imgResName_;
    public boolean hasImgResName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getImgResName() {
      java.lang.Object ref = imgResName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imgResName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImgResNameBytes() {
      java.lang.Object ref = imgResName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imgResName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string createDate = 4;
    public static final int CREATEDATE_FIELD_NUMBER = 4;
    private java.lang.Object createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCreateDate() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          createDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreateDateBytes() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string updateTime = 5;
    public static final int UPDATETIME_FIELD_NUMBER = 5;
    private java.lang.Object updateTime_;
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          updateTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      typeName_ = "";
      imgResName_ = "";
      createDate_ = "";
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImgResName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImgResNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImgResNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_fieldAccessorTable;
      }
      
      // Construct using com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        imgResName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.getDescriptor();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol getDefaultInstanceForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.getDefaultInstance();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol build() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol buildPartial() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol result = new com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.typeName_ = typeName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imgResName_ = imgResName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol) {
          return mergeFrom((com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol other) {
        if (other == com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTypeName()) {
          setTypeName(other.getTypeName());
        }
        if (other.hasImgResName()) {
          setImgResName(other.getImgResName());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTypeName()) {
          
          return false;
        }
        if (!hasImgResName()) {
          
          return false;
        }
        if (!hasCreateDate()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              typeName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imgResName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              createDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string typeName = 2;
      private java.lang.Object typeName_ = "";
      public boolean hasTypeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          typeName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTypeName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      void setTypeName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
      }
      
      // required string imgResName = 3;
      private java.lang.Object imgResName_ = "";
      public boolean hasImgResName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getImgResName() {
        java.lang.Object ref = imgResName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imgResName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImgResName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imgResName_ = value;
        onChanged();
        return this;
      }
      public Builder clearImgResName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imgResName_ = getDefaultInstance().getImgResName();
        onChanged();
        return this;
      }
      void setImgResName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        imgResName_ = value;
        onChanged();
      }
      
      // required string createDate = 4;
      private java.lang.Object createDate_ = "";
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCreateDate() {
        java.lang.Object ref = createDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          createDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreateDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createDate_ = getDefaultInstance().getCreateDate();
        onChanged();
        return this;
      }
      void setCreateDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
      }
      
      // required string updateTime = 5;
      private java.lang.Object updateTime_ = "";
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUpdateTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        updateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      void setUpdateTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        updateTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.pengjun.ka.net.protobuf.ArTypeProtocol)
    }
    
    static {
      defaultInstance = new ArTypeProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pengjun.ka.net.protobuf.ArTypeProtocol)
  }
  
  public interface KaMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .com.pengjun.ka.net.protobuf.MsgType msgType = 1;
    boolean hasMsgType();
    com.pengjun.ka.net.protobuf.KaProtocol.MsgType getMsgType();
    
    // optional .com.pengjun.ka.net.protobuf.MsgRply MsgRply = 2;
    boolean hasMsgRply();
    com.pengjun.ka.net.protobuf.KaProtocol.MsgRply getMsgRply();
    
    // repeated .com.pengjun.ka.net.protobuf.ArProtocol arProtocol = 3;
    java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> 
        getArProtocolList();
    com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol getArProtocol(int index);
    int getArProtocolCount();
    java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder> 
        getArProtocolOrBuilderList();
    com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder getArProtocolOrBuilder(
        int index);
    
    // repeated .com.pengjun.ka.net.protobuf.ArTypeProtocol arTypeProtocol = 4;
    java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> 
        getArTypeProtocolList();
    com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol getArTypeProtocol(int index);
    int getArTypeProtocolCount();
    java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder> 
        getArTypeProtocolOrBuilderList();
    com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder getArTypeProtocolOrBuilder(
        int index);
  }
  public static final class KaMsg extends
      com.google.protobuf.GeneratedMessage
      implements KaMsgOrBuilder {
    // Use KaMsg.newBuilder() to construct.
    private KaMsg(Builder builder) {
      super(builder);
    }
    private KaMsg(boolean noInit) {}
    
    private static final KaMsg defaultInstance;
    public static KaMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public KaMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_KaMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_KaMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .com.pengjun.ka.net.protobuf.MsgType msgType = 1;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private com.pengjun.ka.net.protobuf.KaProtocol.MsgType msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.MsgType getMsgType() {
      return msgType_;
    }
    
    // optional .com.pengjun.ka.net.protobuf.MsgRply MsgRply = 2;
    public static final int MSGRPLY_FIELD_NUMBER = 2;
    private com.pengjun.ka.net.protobuf.KaProtocol.MsgRply msgRply_;
    public boolean hasMsgRply() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.MsgRply getMsgRply() {
      return msgRply_;
    }
    
    // repeated .com.pengjun.ka.net.protobuf.ArProtocol arProtocol = 3;
    public static final int ARPROTOCOL_FIELD_NUMBER = 3;
    private java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> arProtocol_;
    public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> getArProtocolList() {
      return arProtocol_;
    }
    public java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder> 
        getArProtocolOrBuilderList() {
      return arProtocol_;
    }
    public int getArProtocolCount() {
      return arProtocol_.size();
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol getArProtocol(int index) {
      return arProtocol_.get(index);
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder getArProtocolOrBuilder(
        int index) {
      return arProtocol_.get(index);
    }
    
    // repeated .com.pengjun.ka.net.protobuf.ArTypeProtocol arTypeProtocol = 4;
    public static final int ARTYPEPROTOCOL_FIELD_NUMBER = 4;
    private java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> arTypeProtocol_;
    public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> getArTypeProtocolList() {
      return arTypeProtocol_;
    }
    public java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder> 
        getArTypeProtocolOrBuilderList() {
      return arTypeProtocol_;
    }
    public int getArTypeProtocolCount() {
      return arTypeProtocol_.size();
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol getArTypeProtocol(int index) {
      return arTypeProtocol_.get(index);
    }
    public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder getArTypeProtocolOrBuilder(
        int index) {
      return arTypeProtocol_.get(index);
    }
    
    private void initFields() {
      msgType_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgType.REGISTER;
      msgRply_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgRply.SUCCESS;
      arProtocol_ = java.util.Collections.emptyList();
      arTypeProtocol_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getArProtocolCount(); i++) {
        if (!getArProtocol(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getArTypeProtocolCount(); i++) {
        if (!getArTypeProtocol(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, msgRply_.getNumber());
      }
      for (int i = 0; i < arProtocol_.size(); i++) {
        output.writeMessage(3, arProtocol_.get(i));
      }
      for (int i = 0; i < arTypeProtocol_.size(); i++) {
        output.writeMessage(4, arTypeProtocol_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgRply_.getNumber());
      }
      for (int i = 0; i < arProtocol_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, arProtocol_.get(i));
      }
      for (int i = 0; i < arTypeProtocol_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, arTypeProtocol_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.KaMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pengjun.ka.net.protobuf.KaProtocol.KaMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pengjun.ka.net.protobuf.KaProtocol.KaMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_KaMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_net_protobuf_KaMsg_fieldAccessorTable;
      }
      
      // Construct using com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getArProtocolFieldBuilder();
          getArTypeProtocolFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgType.REGISTER;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgRply_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgRply.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (arProtocolBuilder_ == null) {
          arProtocol_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          arProtocolBuilder_.clear();
        }
        if (arTypeProtocolBuilder_ == null) {
          arTypeProtocol_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          arTypeProtocolBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.getDescriptor();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.KaMsg getDefaultInstanceForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.getDefaultInstance();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.KaMsg build() {
        com.pengjun.ka.net.protobuf.KaProtocol.KaMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pengjun.ka.net.protobuf.KaProtocol.KaMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pengjun.ka.net.protobuf.KaProtocol.KaMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.KaMsg buildPartial() {
        com.pengjun.ka.net.protobuf.KaProtocol.KaMsg result = new com.pengjun.ka.net.protobuf.KaProtocol.KaMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgRply_ = msgRply_;
        if (arProtocolBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            arProtocol_ = java.util.Collections.unmodifiableList(arProtocol_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.arProtocol_ = arProtocol_;
        } else {
          result.arProtocol_ = arProtocolBuilder_.build();
        }
        if (arTypeProtocolBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            arTypeProtocol_ = java.util.Collections.unmodifiableList(arTypeProtocol_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.arTypeProtocol_ = arTypeProtocol_;
        } else {
          result.arTypeProtocol_ = arTypeProtocolBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pengjun.ka.net.protobuf.KaProtocol.KaMsg) {
          return mergeFrom((com.pengjun.ka.net.protobuf.KaProtocol.KaMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pengjun.ka.net.protobuf.KaProtocol.KaMsg other) {
        if (other == com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgRply()) {
          setMsgRply(other.getMsgRply());
        }
        if (arProtocolBuilder_ == null) {
          if (!other.arProtocol_.isEmpty()) {
            if (arProtocol_.isEmpty()) {
              arProtocol_ = other.arProtocol_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureArProtocolIsMutable();
              arProtocol_.addAll(other.arProtocol_);
            }
            onChanged();
          }
        } else {
          if (!other.arProtocol_.isEmpty()) {
            if (arProtocolBuilder_.isEmpty()) {
              arProtocolBuilder_.dispose();
              arProtocolBuilder_ = null;
              arProtocol_ = other.arProtocol_;
              bitField0_ = (bitField0_ & ~0x00000004);
              arProtocolBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArProtocolFieldBuilder() : null;
            } else {
              arProtocolBuilder_.addAllMessages(other.arProtocol_);
            }
          }
        }
        if (arTypeProtocolBuilder_ == null) {
          if (!other.arTypeProtocol_.isEmpty()) {
            if (arTypeProtocol_.isEmpty()) {
              arTypeProtocol_ = other.arTypeProtocol_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureArTypeProtocolIsMutable();
              arTypeProtocol_.addAll(other.arTypeProtocol_);
            }
            onChanged();
          }
        } else {
          if (!other.arTypeProtocol_.isEmpty()) {
            if (arTypeProtocolBuilder_.isEmpty()) {
              arTypeProtocolBuilder_.dispose();
              arTypeProtocolBuilder_ = null;
              arTypeProtocol_ = other.arTypeProtocol_;
              bitField0_ = (bitField0_ & ~0x00000008);
              arTypeProtocolBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getArTypeProtocolFieldBuilder() : null;
            } else {
              arTypeProtocolBuilder_.addAllMessages(other.arTypeProtocol_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgType()) {
          
          return false;
        }
        for (int i = 0; i < getArProtocolCount(); i++) {
          if (!getArProtocol(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getArTypeProtocolCount(); i++) {
          if (!getArTypeProtocol(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.pengjun.ka.net.protobuf.KaProtocol.MsgType value = com.pengjun.ka.net.protobuf.KaProtocol.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                msgType_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.pengjun.ka.net.protobuf.KaProtocol.MsgRply value = com.pengjun.ka.net.protobuf.KaProtocol.MsgRply.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                msgRply_ = value;
              }
              break;
            }
            case 26: {
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder subBuilder = com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addArProtocol(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder subBuilder = com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addArTypeProtocol(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .com.pengjun.ka.net.protobuf.MsgType msgType = 1;
      private com.pengjun.ka.net.protobuf.KaProtocol.MsgType msgType_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgType.REGISTER;
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.MsgType getMsgType() {
        return msgType_;
      }
      public Builder setMsgType(com.pengjun.ka.net.protobuf.KaProtocol.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgType.REGISTER;
        onChanged();
        return this;
      }
      
      // optional .com.pengjun.ka.net.protobuf.MsgRply MsgRply = 2;
      private com.pengjun.ka.net.protobuf.KaProtocol.MsgRply msgRply_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgRply.SUCCESS;
      public boolean hasMsgRply() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.MsgRply getMsgRply() {
        return msgRply_;
      }
      public Builder setMsgRply(com.pengjun.ka.net.protobuf.KaProtocol.MsgRply value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        msgRply_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgRply() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgRply_ = com.pengjun.ka.net.protobuf.KaProtocol.MsgRply.SUCCESS;
        onChanged();
        return this;
      }
      
      // repeated .com.pengjun.ka.net.protobuf.ArProtocol arProtocol = 3;
      private java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> arProtocol_ =
        java.util.Collections.emptyList();
      private void ensureArProtocolIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          arProtocol_ = new java.util.ArrayList<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol>(arProtocol_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder> arProtocolBuilder_;
      
      public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> getArProtocolList() {
        if (arProtocolBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arProtocol_);
        } else {
          return arProtocolBuilder_.getMessageList();
        }
      }
      public int getArProtocolCount() {
        if (arProtocolBuilder_ == null) {
          return arProtocol_.size();
        } else {
          return arProtocolBuilder_.getCount();
        }
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol getArProtocol(int index) {
        if (arProtocolBuilder_ == null) {
          return arProtocol_.get(index);
        } else {
          return arProtocolBuilder_.getMessage(index);
        }
      }
      public Builder setArProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol value) {
        if (arProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArProtocolIsMutable();
          arProtocol_.set(index, value);
          onChanged();
        } else {
          arProtocolBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setArProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder builderForValue) {
        if (arProtocolBuilder_ == null) {
          ensureArProtocolIsMutable();
          arProtocol_.set(index, builderForValue.build());
          onChanged();
        } else {
          arProtocolBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addArProtocol(com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol value) {
        if (arProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArProtocolIsMutable();
          arProtocol_.add(value);
          onChanged();
        } else {
          arProtocolBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addArProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol value) {
        if (arProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArProtocolIsMutable();
          arProtocol_.add(index, value);
          onChanged();
        } else {
          arProtocolBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addArProtocol(
          com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder builderForValue) {
        if (arProtocolBuilder_ == null) {
          ensureArProtocolIsMutable();
          arProtocol_.add(builderForValue.build());
          onChanged();
        } else {
          arProtocolBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addArProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder builderForValue) {
        if (arProtocolBuilder_ == null) {
          ensureArProtocolIsMutable();
          arProtocol_.add(index, builderForValue.build());
          onChanged();
        } else {
          arProtocolBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllArProtocol(
          java.lang.Iterable<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol> values) {
        if (arProtocolBuilder_ == null) {
          ensureArProtocolIsMutable();
          super.addAll(values, arProtocol_);
          onChanged();
        } else {
          arProtocolBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearArProtocol() {
        if (arProtocolBuilder_ == null) {
          arProtocol_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          arProtocolBuilder_.clear();
        }
        return this;
      }
      public Builder removeArProtocol(int index) {
        if (arProtocolBuilder_ == null) {
          ensureArProtocolIsMutable();
          arProtocol_.remove(index);
          onChanged();
        } else {
          arProtocolBuilder_.remove(index);
        }
        return this;
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder getArProtocolBuilder(
          int index) {
        return getArProtocolFieldBuilder().getBuilder(index);
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder getArProtocolOrBuilder(
          int index) {
        if (arProtocolBuilder_ == null) {
          return arProtocol_.get(index);  } else {
          return arProtocolBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder> 
           getArProtocolOrBuilderList() {
        if (arProtocolBuilder_ != null) {
          return arProtocolBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arProtocol_);
        }
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder addArProtocolBuilder() {
        return getArProtocolFieldBuilder().addBuilder(
            com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance());
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder addArProtocolBuilder(
          int index) {
        return getArProtocolFieldBuilder().addBuilder(
            index, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance());
      }
      public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder> 
           getArProtocolBuilderList() {
        return getArProtocolFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder> 
          getArProtocolFieldBuilder() {
        if (arProtocolBuilder_ == null) {
          arProtocolBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder>(
                  arProtocol_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          arProtocol_ = null;
        }
        return arProtocolBuilder_;
      }
      
      // repeated .com.pengjun.ka.net.protobuf.ArTypeProtocol arTypeProtocol = 4;
      private java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> arTypeProtocol_ =
        java.util.Collections.emptyList();
      private void ensureArTypeProtocolIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          arTypeProtocol_ = new java.util.ArrayList<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol>(arTypeProtocol_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder> arTypeProtocolBuilder_;
      
      public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> getArTypeProtocolList() {
        if (arTypeProtocolBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arTypeProtocol_);
        } else {
          return arTypeProtocolBuilder_.getMessageList();
        }
      }
      public int getArTypeProtocolCount() {
        if (arTypeProtocolBuilder_ == null) {
          return arTypeProtocol_.size();
        } else {
          return arTypeProtocolBuilder_.getCount();
        }
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol getArTypeProtocol(int index) {
        if (arTypeProtocolBuilder_ == null) {
          return arTypeProtocol_.get(index);
        } else {
          return arTypeProtocolBuilder_.getMessage(index);
        }
      }
      public Builder setArTypeProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol value) {
        if (arTypeProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.set(index, value);
          onChanged();
        } else {
          arTypeProtocolBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setArTypeProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder builderForValue) {
        if (arTypeProtocolBuilder_ == null) {
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.set(index, builderForValue.build());
          onChanged();
        } else {
          arTypeProtocolBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addArTypeProtocol(com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol value) {
        if (arTypeProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.add(value);
          onChanged();
        } else {
          arTypeProtocolBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addArTypeProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol value) {
        if (arTypeProtocolBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.add(index, value);
          onChanged();
        } else {
          arTypeProtocolBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addArTypeProtocol(
          com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder builderForValue) {
        if (arTypeProtocolBuilder_ == null) {
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.add(builderForValue.build());
          onChanged();
        } else {
          arTypeProtocolBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addArTypeProtocol(
          int index, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder builderForValue) {
        if (arTypeProtocolBuilder_ == null) {
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.add(index, builderForValue.build());
          onChanged();
        } else {
          arTypeProtocolBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllArTypeProtocol(
          java.lang.Iterable<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol> values) {
        if (arTypeProtocolBuilder_ == null) {
          ensureArTypeProtocolIsMutable();
          super.addAll(values, arTypeProtocol_);
          onChanged();
        } else {
          arTypeProtocolBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearArTypeProtocol() {
        if (arTypeProtocolBuilder_ == null) {
          arTypeProtocol_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          arTypeProtocolBuilder_.clear();
        }
        return this;
      }
      public Builder removeArTypeProtocol(int index) {
        if (arTypeProtocolBuilder_ == null) {
          ensureArTypeProtocolIsMutable();
          arTypeProtocol_.remove(index);
          onChanged();
        } else {
          arTypeProtocolBuilder_.remove(index);
        }
        return this;
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder getArTypeProtocolBuilder(
          int index) {
        return getArTypeProtocolFieldBuilder().getBuilder(index);
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder getArTypeProtocolOrBuilder(
          int index) {
        if (arTypeProtocolBuilder_ == null) {
          return arTypeProtocol_.get(index);  } else {
          return arTypeProtocolBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder> 
           getArTypeProtocolOrBuilderList() {
        if (arTypeProtocolBuilder_ != null) {
          return arTypeProtocolBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arTypeProtocol_);
        }
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder addArTypeProtocolBuilder() {
        return getArTypeProtocolFieldBuilder().addBuilder(
            com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.getDefaultInstance());
      }
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder addArTypeProtocolBuilder(
          int index) {
        return getArTypeProtocolFieldBuilder().addBuilder(
            index, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.getDefaultInstance());
      }
      public java.util.List<com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder> 
           getArTypeProtocolBuilderList() {
        return getArTypeProtocolFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder> 
          getArTypeProtocolFieldBuilder() {
        if (arTypeProtocolBuilder_ == null) {
          arTypeProtocolBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder, com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocolOrBuilder>(
                  arTypeProtocol_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          arTypeProtocol_ = null;
        }
        return arTypeProtocolBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.pengjun.ka.net.protobuf.KaMsg)
    }
    
    static {
      defaultInstance = new KaMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pengjun.ka.net.protobuf.KaMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pengjun_ka_net_protobuf_ArProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pengjun_ka_net_protobuf_ArProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pengjun_ka_net_protobuf_KaMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pengjun_ka_net_protobuf_KaMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/pengjun/ka/net/protobuf/KeepAccoun" +
      "t.proto\022\033com.pengjun.ka.net.protobuf\"r\n\n" +
      "ArProtocol\022\n\n\002id\030\001 \001(\005\022\017\n\007account\030\002 \002(\002\022" +
      "\016\n\006typeId\030\003 \002(\005\022\022\n\ncreateDate\030\004 \002(\t\022\017\n\007c" +
      "omment\030\005 \001(\t\022\022\n\nupdateTime\030\006 \002(\t\"j\n\016ArTy" +
      "peProtocol\022\n\n\002id\030\001 \001(\005\022\020\n\010typeName\030\002 \002(\t" +
      "\022\022\n\nimgResName\030\003 \002(\t\022\022\n\ncreateDate\030\004 \002(\t" +
      "\022\022\n\nupdateTime\030\005 \002(\t\"\367\001\n\005KaMsg\0225\n\007msgTyp" +
      "e\030\001 \002(\0162$.com.pengjun.ka.net.protobuf.Ms" +
      "gType\0225\n\007MsgRply\030\002 \001(\0162$.com.pengjun.ka.",
      "net.protobuf.MsgRply\022;\n\narProtocol\030\003 \003(\013" +
      "2\'.com.pengjun.ka.net.protobuf.ArProtoco" +
      "l\022C\n\016arTypeProtocol\030\004 \003(\0132+.com.pengjun." +
      "ka.net.protobuf.ArTypeProtocol*;\n\007MsgTyp" +
      "e\022\014\n\010REGISTER\020\001\022\t\n\005LOGIN\020\002\022\n\n\006BACKUP\020\003\022\013" +
      "\n\007RESTORE\020\004*\"\n\007MsgRply\022\013\n\007SUCCESS\020\001\022\n\n\006F" +
      "AILED\020\002B)\n\033com.pengjun.ka.net.protobufB\n" +
      "KaProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_pengjun_ka_net_protobuf_ArProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_pengjun_ka_net_protobuf_ArProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pengjun_ka_net_protobuf_ArProtocol_descriptor,
              new java.lang.String[] { "Id", "Account", "TypeId", "CreateDate", "Comment", "UpdateTime", },
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.class,
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder.class);
          internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pengjun_ka_net_protobuf_ArTypeProtocol_descriptor,
              new java.lang.String[] { "Id", "TypeName", "ImgResName", "CreateDate", "UpdateTime", },
              com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.class,
              com.pengjun.ka.net.protobuf.KaProtocol.ArTypeProtocol.Builder.class);
          internal_static_com_pengjun_ka_net_protobuf_KaMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_pengjun_ka_net_protobuf_KaMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pengjun_ka_net_protobuf_KaMsg_descriptor,
              new java.lang.String[] { "MsgType", "MsgRply", "ArProtocol", "ArTypeProtocol", },
              com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.class,
              com.pengjun.ka.net.protobuf.KaProtocol.KaMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
