// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: KeepAccount.proto

package com.pengjun.ka.net.protobuf;

public final class KaProtocol {
  private KaProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ArProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required float account = 2;
    boolean hasAccount();
    float getAccount();
    
    // required int32 typeId = 3;
    boolean hasTypeId();
    int getTypeId();
    
    // required string createDate = 4;
    boolean hasCreateDate();
    String getCreateDate();
    
    // optional string comment = 5;
    boolean hasComment();
    String getComment();
    
    // required string updateTime = 6;
    boolean hasUpdateTime();
    String getUpdateTime();
  }
  public static final class ArProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ArProtocolOrBuilder {
    // Use ArProtocol.newBuilder() to construct.
    private ArProtocol(Builder builder) {
      super(builder);
    }
    private ArProtocol(boolean noInit) {}
    
    private static final ArProtocol defaultInstance;
    public static ArProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required float account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private float account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public float getAccount() {
      return account_;
    }
    
    // required int32 typeId = 3;
    public static final int TYPEID_FIELD_NUMBER = 3;
    private int typeId_;
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getTypeId() {
      return typeId_;
    }
    
    // required string createDate = 4;
    public static final int CREATEDATE_FIELD_NUMBER = 4;
    private java.lang.Object createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCreateDate() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          createDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreateDateBytes() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string comment = 5;
    public static final int COMMENT_FIELD_NUMBER = 5;
    private java.lang.Object comment_;
    public boolean hasComment() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          comment_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string updateTime = 6;
    public static final int UPDATETIME_FIELD_NUMBER = 6;
    private java.lang.Object updateTime_;
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          updateTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      account_ = 0F;
      typeId_ = 0;
      createDate_ = "";
      comment_ = "";
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getCommentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, account_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, typeId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getCommentBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pengjun.ka.net.protobuf.KaProtocol.ArProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArProtocol_fieldAccessorTable;
      }
      
      // Construct using com.pengjun.ka.protobuf.KaProtocol.ArProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        createDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDescriptor();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol getDefaultInstanceForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol build() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol buildPartial() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol result = new com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.comment_ = comment_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol) {
          return mergeFrom((com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol other) {
        if (other == com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasComment()) {
          setComment(other.getComment());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasAccount()) {
          
          return false;
        }
        if (!hasTypeId()) {
          
          return false;
        }
        if (!hasCreateDate()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              account_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              typeId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              createDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              comment_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required float account = 2;
      private float account_ ;
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getAccount() {
        return account_;
      }
      public Builder setAccount(float value) {
        bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = 0F;
        onChanged();
        return this;
      }
      
      // required int32 typeId = 3;
      private int typeId_ ;
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getTypeId() {
        return typeId_;
      }
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000004;
        typeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        typeId_ = 0;
        onChanged();
        return this;
      }
      
      // required string createDate = 4;
      private java.lang.Object createDate_ = "";
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCreateDate() {
        java.lang.Object ref = createDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          createDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreateDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createDate_ = getDefaultInstance().getCreateDate();
        onChanged();
        return this;
      }
      void setCreateDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
      }
      
      // optional string comment = 5;
      private java.lang.Object comment_ = "";
      public boolean hasComment() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setComment(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        comment_ = value;
        onChanged();
        return this;
      }
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000010);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      void setComment(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        comment_ = value;
        onChanged();
      }
      
      // required string updateTime = 6;
      private java.lang.Object updateTime_ = "";
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUpdateTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        updateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      void setUpdateTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        updateTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.pengjun.ka.protobuf.ArProtocol)
    }
    
    static {
      defaultInstance = new ArProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pengjun.ka.protobuf.ArProtocol)
  }
  
  public interface ArTpyeProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string typeName = 2;
    boolean hasTypeName();
    String getTypeName();
    
    // required string imgResName = 3;
    boolean hasImgResName();
    String getImgResName();
    
    // required string createDate = 4;
    boolean hasCreateDate();
    String getCreateDate();
    
    // required string updateTime = 5;
    boolean hasUpdateTime();
    String getUpdateTime();
  }
  public static final class ArTpyeProtocol extends
      com.google.protobuf.GeneratedMessage
      implements ArTpyeProtocolOrBuilder {
    // Use ArTpyeProtocol.newBuilder() to construct.
    private ArTpyeProtocol(Builder builder) {
      super(builder);
    }
    private ArTpyeProtocol(boolean noInit) {}
    
    private static final ArTpyeProtocol defaultInstance;
    public static ArTpyeProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public ArTpyeProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string typeName = 2;
    public static final int TYPENAME_FIELD_NUMBER = 2;
    private java.lang.Object typeName_;
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTypeName() {
      java.lang.Object ref = typeName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          typeName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeNameBytes() {
      java.lang.Object ref = typeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        typeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string imgResName = 3;
    public static final int IMGRESNAME_FIELD_NUMBER = 3;
    private java.lang.Object imgResName_;
    public boolean hasImgResName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getImgResName() {
      java.lang.Object ref = imgResName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imgResName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImgResNameBytes() {
      java.lang.Object ref = imgResName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imgResName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string createDate = 4;
    public static final int CREATEDATE_FIELD_NUMBER = 4;
    private java.lang.Object createDate_;
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getCreateDate() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          createDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCreateDateBytes() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string updateTime = 5;
    public static final int UPDATETIME_FIELD_NUMBER = 5;
    private java.lang.Object updateTime_;
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          updateTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = 0;
      typeName_ = "";
      imgResName_ = "";
      createDate_ = "";
      updateTime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImgResName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImgResNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUpdateTimeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImgResNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUpdateTimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pengjun.ka.net.protobuf.KaProtocol.internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_fieldAccessorTable;
      }
      
      // Construct using com.pengjun.ka.protobuf.KaProtocol.ArTpyeProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        typeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        imgResName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        updateTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol.getDescriptor();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol getDefaultInstanceForType() {
        return com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol.getDefaultInstance();
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol build() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol buildPartial() {
        com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol result = new com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.typeName_ = typeName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.imgResName_ = imgResName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.updateTime_ = updateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol) {
          return mergeFrom((com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol other) {
        if (other == com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTypeName()) {
          setTypeName(other.getTypeName());
        }
        if (other.hasImgResName()) {
          setImgResName(other.getImgResName());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        if (other.hasUpdateTime()) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTypeName()) {
          
          return false;
        }
        if (!hasImgResName()) {
          
          return false;
        }
        if (!hasCreateDate()) {
          
          return false;
        }
        if (!hasUpdateTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              typeName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              imgResName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              createDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              updateTime_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string typeName = 2;
      private java.lang.Object typeName_ = "";
      public boolean hasTypeName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTypeName() {
        java.lang.Object ref = typeName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          typeName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTypeName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        typeName_ = getDefaultInstance().getTypeName();
        onChanged();
        return this;
      }
      void setTypeName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        typeName_ = value;
        onChanged();
      }
      
      // required string imgResName = 3;
      private java.lang.Object imgResName_ = "";
      public boolean hasImgResName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getImgResName() {
        java.lang.Object ref = imgResName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imgResName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImgResName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        imgResName_ = value;
        onChanged();
        return this;
      }
      public Builder clearImgResName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        imgResName_ = getDefaultInstance().getImgResName();
        onChanged();
        return this;
      }
      void setImgResName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        imgResName_ = value;
        onChanged();
      }
      
      // required string createDate = 4;
      private java.lang.Object createDate_ = "";
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getCreateDate() {
        java.lang.Object ref = createDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          createDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCreateDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createDate_ = getDefaultInstance().getCreateDate();
        onChanged();
        return this;
      }
      void setCreateDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        createDate_ = value;
        onChanged();
      }
      
      // required string updateTime = 5;
      private java.lang.Object updateTime_ = "";
      public boolean hasUpdateTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUpdateTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        updateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      void setUpdateTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        updateTime_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.pengjun.ka.protobuf.ArTpyeProtocol)
    }
    
    static {
      defaultInstance = new ArTpyeProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.pengjun.ka.protobuf.ArTpyeProtocol)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pengjun_ka_protobuf_ArProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pengjun_ka_protobuf_ArProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021KeepAccount.proto\022\027com.pengjun.ka.prot" +
      "obuf\"r\n\nArProtocol\022\n\n\002id\030\001 \002(\005\022\017\n\007accoun" +
      "t\030\002 \002(\002\022\016\n\006typeId\030\003 \002(\005\022\022\n\ncreateDate\030\004 " +
      "\002(\t\022\017\n\007comment\030\005 \001(\t\022\022\n\nupdateTime\030\006 \002(\t" +
      "\"j\n\016ArTpyeProtocol\022\n\n\002id\030\001 \002(\005\022\020\n\010typeNa" +
      "me\030\002 \002(\t\022\022\n\nimgResName\030\003 \002(\t\022\022\n\ncreateDa" +
      "te\030\004 \002(\t\022\022\n\nupdateTime\030\005 \002(\tB%\n\027com.peng" +
      "jun.ka.protobufB\nKaProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_pengjun_ka_protobuf_ArProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_pengjun_ka_protobuf_ArProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pengjun_ka_protobuf_ArProtocol_descriptor,
              new java.lang.String[] { "Id", "Account", "TypeId", "CreateDate", "Comment", "UpdateTime", },
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.class,
              com.pengjun.ka.net.protobuf.KaProtocol.ArProtocol.Builder.class);
          internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_pengjun_ka_protobuf_ArTpyeProtocol_descriptor,
              new java.lang.String[] { "Id", "TypeName", "ImgResName", "CreateDate", "UpdateTime", },
              com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol.class,
              com.pengjun.ka.net.protobuf.KaProtocol.ArTpyeProtocol.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
